# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1.xci
# IP: The module: 'FIR_FIFO1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_FIFO1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_FIFO1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1.xci
# IP: The module: 'FIR_FIFO1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_FIFO1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/surin/Documents/project/4TAP_FIR_FILTER_IMPL/modules/ip/FIR_FIFO1_2/FIR_FIFO1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_FIFO1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
